"""empty message

Revision ID: ca1dfb06cab1
Revises: 
Create Date: 2018-04-30 16:14:15.812000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1dfb06cab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dytt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('translate_name', sa.String(length=300), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('product_site', sa.String(length=100), nullable=False),
    sa.Column('classify', sa.String(length=100), nullable=False),
    sa.Column('actors', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=False),
    sa.Column('screenshot_url', sa.String(length=500), nullable=False),
    sa.Column('thunder_url', sa.String(length=500), nullable=False),
    sa.Column('magnet_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dytt')
    # ### end Alembic commands ###
